/**
 *
 *  @file GameExportAsset.hpp
 *  @author Gaspard Kirira
 *
 *  Copyright 2026, Gaspard Kirira.
 *  All rights reserved.
 *  https://github.com/vixcpp/game
 *
 *  Use of this source code is governed by a MIT license
 *  that can be found in the LICENSE file.
 *
 *  Vix.cpp
 *
 */
#ifndef VIX_GAME_GAME_EXPORT_ASSET_HPP
#define VIX_GAME_GAME_EXPORT_ASSET_HPP

#include <cstdint>
#include <string>

#include <vix/json/json.hpp>

namespace vix::game
{
  /**
   * @brief Asset type detected during game export.
   */
  enum class GameExportAssetType
  {
    /**
     * @brief Image asset.
     */
    Image,

    /**
     * @brief Text-like asset.
     */
    Text,

    /**
     * @brief Binary or unknown asset.
     */
    Binary
  };

  /**
   * @brief Convert an export asset type to a stable string.
   */
  [[nodiscard]] inline const char *to_string(
      GameExportAssetType type) noexcept
  {
    switch (type)
    {
    case GameExportAssetType::Image:
      return "image";

    case GameExportAssetType::Text:
      return "text";

    case GameExportAssetType::Binary:
      return "binary";

    default:
      return "binary";
    }
  }

  /**
   * @brief Asset entry generated by the export asset pipeline.
   *
   * GameExportAsset is written into export.json so tools, editors, and future
   * CLI commands can inspect which assets were exported.
   */
  class GameExportAsset
  {
  public:
    /**
     * @brief Asset path relative to the asset root.
     */
    std::string path{};

    /**
     * @brief Detected asset type.
     */
    GameExportAssetType type{GameExportAssetType::Binary};

    /**
     * @brief Asset size in bytes.
     */
    std::uint64_t size_bytes{0};

    /**
     * @brief Convert this asset entry to JSON.
     */
    [[nodiscard]] vix::json::Json to_json() const
    {
      vix::json::Json json;

      json["path"] = path;
      json["type"] = to_string(type);
      json["size_bytes"] = size_bytes;

      return json;
    }
  };

} // namespace vix::game

#endif // VIX_GAME_GAME_EXPORT_ASSET_HPP
