/**
 *
 *  @file GameExportManifest.hpp
 *  @author Gaspard Kirira
 *
 *  Copyright 2026, Gaspard Kirira.
 *  All rights reserved.
 *  https://github.com/vixcpp/game
 *
 *  Use of this source code is governed by a MIT license
 *  that can be found in the LICENSE file.
 *
 *  Vix.cpp
 *
 */
#ifndef VIX_GAME_GAME_EXPORT_MANIFEST_HPP
#define VIX_GAME_GAME_EXPORT_MANIFEST_HPP

#include <cstdint>
#include <string>
#include <vector>

#include <vix/game/GameExportAsset.hpp>
#include <vix/game/GameResult.hpp>
#include <vix/json/json.hpp>

namespace vix::game
{
  /**
   * @brief Metadata generated after exporting a game project.
   *
   * GameExportManifest is written to export.json inside the exported game
   * directory. It describes what was exported and where.
   */
  class GameExportManifest
  {
  public:
    /**
     * @brief Exported game name.
     */
    std::string name{"game"};

    /**
     * @brief Exported game version.
     */
    std::string version{"0.1.0"};

    /**
     * @brief Asset root used during export.
     */
    std::string asset_root{"assets"};

    /**
     * @brief Exported assets discovered by the asset pipeline.
     */
    std::vector<GameExportAsset> assets{};

    /**
     * @brief Final output path.
     */
    std::string output_path{};

    /**
     * @brief Number of copied files.
     */
    std::uint64_t copied_files{0};

    /**
     * @brief Number of copied directories.
     */
    std::uint64_t copied_directories{0};

    /**
     * @brief Export timestamp.
     *
     * V5 keeps this as a simple UTC-like string generated by the exporter.
     */
    std::string build_date{};

    /**
     * @brief Convert this manifest to JSON.
     */
    [[nodiscard]] vix::json::Json to_json() const;

    /**
     * @brief Save this manifest to a file.
     */
    [[nodiscard]] GameBoolResult save_file(const std::string &path) const;
  };

} // namespace vix::game

#endif // VIX_GAME_GAME_EXPORT_MANIFEST_HPP
